### ISSUE TITLE
How to show verbose output when downloading a file?

### ISSUE THREAD

**Issue by hillz1** [prasmussen/gdrive#100]
How do you show verbose output when downloading a file? When I download a file with
`drive download --id XXX`

It doesn't show any download progress.

**Comment by prasmussen** [comment]
The current version does not have any verbose output. gdrive 2.0 will have a progress indicator, and will probably be ready later this month.

**Comment by hillz1** [comment]
That's great, I'm looking forward to that. Can this be installed in openwrt ? I've only tried installing it in ubuntu 14.04 and I thought that it'd be good if it could also run on openwrt routers.

**Comment by prasmussen** [comment]
That depends on the processor type in your router. The arm or rpi build might work.

**Comment by freeman212** [comment]
> gdrive 2.0 will have a progress indicator, and will probably be ready later this month.

great news, man! been waiting forever for this feature.

**Comment by prasmussen** [comment]
gdrive 2 is ready and has a basic progress indicator enabled by default for larger files.

**Comment by 7yl4r** [comment]
Progress bars are a great improvement, but a `--verbose` option could still be useful I think.

I'm `sync`ing a large folder right now though and it does *seem* to be hung at "Collecting local and remote file information..."
