### ISSUE TITLE
code.google.com/p/goauth2/oauth not available

### ISSUE THREAD

**Issue by xrobin** [prasmussen/gdrive#104]
It looks like google removed goauth2 from their server. When I tried to grab it with 'go get' I get the following error:

xavier@congo:~/go$ go get github.com/prasmussen/gdrive
package code.google.com/p/goauth2/oauth: unable to detect version control system for code.google.com/ path

The page suggests to use golang.org/x/oauth2 instead.

**Comment by xrobin** [comment]
However it looks like I can not just replace the import with golang.org/x/oauth2/oauth. Other things seems to have changed.

**Comment by prasmussen** [comment]
I'm currently working on gdrive 2.0 which uses golang.org/x/oauth2/oauth: [https://github.com/prasmussen/gdrive/blob/2.0-wip/auth/oauth.go](https://github.com/prasmussen/gdrive/blob/2.0-wip/auth/oauth.go)
