### ISSUE TITLE
`googleapi: Error 500` with `drive list`

### ISSUE THREAD

**Issue by quinncomendant** [prasmussen/gdrive#105]
I've just setup a new OS X 10.11 macbook and have installed the latest drive (`drive-osx-x64`) and copied my old `~/.gdrive/` from an old computer. Uploading works fine, but `drive list` does not. I get this error:

    [q@localhost/0 ~] drive list
    googleapi: Error 500: Internal Error, internalError

Is there a way I can troubleshoot this (is there a log, debug, or trace option)?

**Comment by Drezzler** [comment]
Please check this https://github.com/prasmussen/gdrive/issues/96

**Comment by quinncomendant** [comment]
Yes, that solved it! Thanks!

**Comment by prasmussen** [comment]
gdrive 2 defaults to max 30 files which should solve this.
