### ISSUE TITLE
Few questions

### ISSUE THREAD

**Issue by combucha** [prasmussen/gdrive#112]
Hi
1. Why "-rename" option doesn't exist in gdrive?
2. Why gdrive using decimal multiplier of MB in filesize instead of worldwide 1024*1024 B?
3. In new version after upload gdrive flushes:
- Uploading photo.jpg
- Uploaded 0B0t3ByL3x0tfai0wdHFyNGhVS1E at 66.5 KB/s, total 127.9 KB

Older build printed out more; owner, md5sum, etc... New one-line report was intentional?

**Comment by Drezzler** [comment]
1. Currently you cannot rename a file but can update the file by using `update` command.
2. To get accurate file info when user asks for filesize to be shown in bytes ,its just a guess though.
3. @prasmussen  - can you please chime in ?

**Comment by combucha** [comment]
Quite interesting community here.
Especially gdrive author responses :)
Dunno why, but they are invisible.
