### ISSUE TITLE
Flag -i should not be needed

### ISSUE THREAD

**Issue by crosbymichael** [prasmussen/gdrive#12]
When working with files we could not need to provide `-i` with the id, it should be part of the args.

```bash
gdrive info -i aldksjfladskjf
gdrive info aldksjfladskjf
```

I'm not too familiar with the flags package that you are using.  Do you know if the package supports taking args and populating the `Options` struct?

**Comment by prasmussen** [comment]
The argument parser has been replaced in in gdrive 2 and `-i` is no longer required.
