### ISSUE TITLE
linux_arm build error: constant 285870213051353865 overflows big.Word

### ISSUE THREAD

**Issue by willemw12** [prasmussen/gdrive#122]
On linux_arm, a dependency fails to build.

Question: do you have the same problem when trying to build the "gdrive-linux-arm" download file?

    $ go get github.com/prasmussen/gdrive
    # github.com/soniakeys/graph
    ../go/src/github.com/soniakeys/graph/bits.go:71: constant 285870213051353865 overflows big.Word

**Comment by andyferra** [comment]
+1

**Comment by prasmussen** [comment]
You might have better luck compiling now, a change was done to the graph library 3 days ago regarding 32-bit support: soniakeys/graph@a9791af
Just make sure you get the latest version of the graph library.

**Comment by willemw12** [comment]
Unfortunately not. See my comment on https://github.com/soniakeys/graph/issues/41.

**Comment by soniakeys** [comment]
The graph library is changed hopefully to support arm but I have no way to test it.  Confirmation that it works for arm would be much appreciated.

**Comment by willemw12** [comment]
Gdrive builds and runs fine now on "linux_arm".

**Comment by prasmussen** [comment]
Excellent, thanks @soniakeys
