### ISSUE TITLE
Who/what am I authorizing when I paste this code back in to gdrive?

### ISSUE THREAD

**Issue by DuncanMarshall** [prasmussen/gdrive#124]
So not to be too mistrusting, but what and/or who am I entrusting my Drive account to when I authorize this application?

Is my authorization bound to the developer's API key or some similar, and what's to stop that being compromised?

**Comment by prasmussen** [comment]
When you give gdrive permission to access your drive it is allowed to access your drive by using an access/refresh token. The access/refresh token is obtained by exchanging the verification code you enter the first time, and the tokens are saved inside the ~/.gdrive directory. Anyone with access to the tokens will be able to access your drive.

More details can be found here: [https://developers.google.com/identity/protocols/OAuth2InstalledApp](https://developers.google.com/identity/protocols/OAuth2InstalledApp)

If you lose your tokens you can revoke the gdrive permission here to invalidate them: [https://security.google.com/settings/security/permissions](https://security.google.com/settings/security/permissions)
