### ISSUE TITLE
googleapi error 400 after passing list with -q (query)

### ISSUE THREAD

**Issue by wkoszek** [prasmussen/gdrive#128]
To get the folder by name, I've always used:

`gdrive list -q "query"`

example:

`gdrive list -q "title = \"11_BLOG\""`

I just compiled `gdrive` on my fresh El Capitain, and I'm getting:

```
wk:repos/me/scripts> ~/Downloads/gdrive list -q "title = \"11_BLOG\""
Failed to list files: googleapi: Error 400: Invalid Value, invalid
```

I tried to get pre-built binary, but the result is the same. Did something change?

**Comment by prasmussen** [comment]
Yeah, the api changed, the title field is now called `name`. Overview can be found here: [https://developers.google.com/drive/search-parameters](https://developers.google.com/drive/search-parameters)
