### ISSUE TITLE
Build system for different binaries

### ISSUE THREAD

**Issue by matthill** [prasmussen/gdrive#142]
Very cool project!  Thanks for making this available.  The CLI is simple and perfectly useful.

This isn't an issue, I just wanted to ask you a question.  I haven't seen too many projects with all of the binaries pre-built for so many different architectures.  That makes it so easy to download and start using.  I'm curious, what build system are you using?  I'd like to do something similar for a project I'm involved with.

**Comment by prasmussen** [comment]
It's because of golang's very good cross compile support I'm able to create binaries for all those platforms. I'm using [this](https://github.com/prasmussen/gdrive/blob/master/_release/build-all.sh) bash script to compile to all platforms from my OSX machine.
