### ISSUE TITLE
Crontab - Upload to Google Drive

### ISSUE THREAD

**Issue by ChrisMann89** [prasmussen/gdrive#151]
I noticed previous dialogue regarding crontabs but couldn't find a solution to my problem.

I have created a script that will take backups of MySQL databases and upload a compressed tar.gz file to Google Drive. This works fine on the command line, but the upload doesn't happen when called via crontab. It is worth noting here that the cron does create a file, so is set up correctly.

Here's the code (feel free to use it yourselves):
`
<i>#!/bin/sh</i>
<i># Create a backup of all MySQL databases</i>

<i># Create a temporary directory to store the MySQL databases</i>
mkdir /$( date '+%Y-%m-%d' )

<i># Enter the temporary directory created above</i>
cd /$( date '+%Y-%m-%d' )

<i># Create a dump of each database</i>
mysql -u user -ppass -e 'show databases' | while read dbname; do mysqldump -u user -ppass -h localhost "$dbname" > "$dbname".sql; done

<i># Create a tar.gz archive, consisting of all database backups</i>
tar -zcf /$( date '+%Y-%m-%d' ).tar.gz /$( date '+%Y-%m-%d' )

<i># Transfer the tar.gz archive to Google Drive</i>
gdrive upload --parent XXXXX /$( date '+%Y-%m-%d' ).tar.gz

<i># Remove the temporary directory created at the top of the script</i>
rm -rf /$( date '+%Y-%m-%d' )

<i># Finally, remove the tar.gz archive from the server</i>
rm -rf /$( date '+%Y-%m-%d' ).tar.gz
`

Somewhere, somehow, I get the feeling the cron doesn't recognise the gdrive command. Everything else works flawlessly, so what would people recommend in order for the upload to work automatically.

**Comment by prasmussen** [comment]
gdrive is probably not in path.
You can set the path manually at the top of your crontab by copying the output of `echo $PATH`. Mine looks like this:
```bash
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
```
or you could use the full path to the gdrive binary in your script.

**Comment by ChrisMann89** [comment]
Awesome. A quick response and one that worked first time.

The top of my script now reads as follows:

`#!/bin/sh`
`PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin`

Thank you.

**Comment by abdo0** [comment]
i have the same issue i try to insert 
`PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin`
but still crontab didn't execute the gdrive command in bash 
any one have solution?

**Comment by whitehorse0** [comment]
@abdo0 you can found this soulution in here
[medium](https://medium.com/auto-backup-mysql-to-google-drive/auto-backup-mysql-to-google-drive-c8b2178b097e)

**Comment by arthurAbitante** [comment]
I've been with this same problem. Do you test all commands manually without in crontab? I imagine that you install gdrive with linuxbrew. The good way to install it's downloading the executable, change the name to "gdrive" and copying it to /usr/bin.
