### ISSUE TITLE
Limited upload speed

### ISSUE THREAD

**Issue by combucha** [prasmussen/gdrive#155]
Hi, anobody experiencing different upload speed between browser and gdrive?
My browser up reaches 5 Mbps with no problem, while gdvive speed stuck at 2.6.
Tried --chunksize option but it does not help at all.

**Comment by hex** [comment]
Happens to me as well.

**Comment by hex** [comment]
Using ```--chunksize 104857600``` seemed to help. Try that.

**Comment by combucha** [comment]
Not in my case.
I fixed capped speed by playing with system registry entries (TcpWindowSize and AFD buffers).
Maybe it's related with old systems only (xp and below),
http://www.speedguide.net/forums/showthread.php?85875-TCP-IP-amp-AFD-Parameters
