### ISSUE TITLE
How do I list files in a GDrive directory

### ISSUE THREAD

**Issue by mikeyfev1** [prasmussen/gdrive#159]
I am using an automation tool which automatically reads new GMail and files the attachments on my Google drive in folders.  How do I use the **GDrive** command to list the files in the folder?

**Comment by archeious** [comment]
You need to get the ID of the folder this can be done with the list command.  If there are a lot of object you will need to use the query option to narrow it down.  If you want a list of objects in the root you can use 'root' as the ID e.g.,

./gdrive list --query " 'root' in parents"
or 

./gdrive list --query " 'IdOfTheParentFolder' in parents"

**Comment by alexanderkjeldaas** [comment]
I also need this.

**Comment by taewookim** [comment]
I must be a complete dumbass

parent_folder (parent_id)
 └─child_folder (child_id)

So if I want to get the content of the child_folder, is the command:

`gdrive` list --query "child_id"`

?

**Comment by danieladamspencer** [comment]
@taewookim Are you using the folder name for the parent_id, or are you using the actual ID hash? Also, you need to include the "in parents" part in your query. For example:

./gdrive list --query " 'child_id' in parents"
