### ISSUE TITLE
Improving documentation

### ISSUE THREAD

**Issue by celicoo** [prasmussen/gdrive#162]
@prasmussen U really need improve this documentation. The CLI is awesome, but i'm having a hard time to figure out things..

I have revoked the access of gdrive in my google account, and i can't figure it out how to connect again.

`gdrive --config (dir)` isn't working, and i can't find the path for the token in my Ubuntu. Can u help?

Thanks!

**Comment by prasmussen** [comment]
You can delete the .gdrive directory in your home directory to reset all state. The path to the config directory is also shown in the description for the `--config` flag if you write for example `gdrive help list`.
