### ISSUE TITLE
update file

### ISSUE THREAD

**Issue by theunbelievablerepo** [prasmussen/gdrive#18]
Hi
Great work, (I like cmd line!). Could you please add 'update' looks like it is possible with: https://developers.google.com/drive/v2/reference/files/update
I am not a go programmer!
Many thanks

**Comment by m93a** [comment]
@gedw99 What? The link blophysics referenced **is** on their API page. What's the problem?

**Comment by gedw99** [comment]
Ah yes found it !! Thanks

**Comment by ljoli** [comment]
Hi everybody ! !

According to your discussion. 
What is the command line for update a file ?

Regards

**Comment by mingram8** [comment]
Did anybody figure this out?

**Comment by prasmussen** [comment]
Im currently working on gdrive v2, which will support update.

**Comment by a-legrand** [comment]
+1 !

**Comment by prasmussen** [comment]
gdrive 2 is now available.
```
$ gdrive update 0B3X9GlR6EmbnNTk0SkV0bm5Hd0E gdrive-osx-x64
Uploading gdrive-osx-x64
Updated 0B3X9GlR6EmbnNTk0SkV0bm5Hd0E at 2.0 MB/s, total 8.3 MB
```

```
$ gdrive revision list 0B3X9GlR6EmbnNTk0SkV0bm5Hd0E
Id                                                    Name             Size     Modified              KeepForever
0B3X9GlR6EmbnOFlHSTZQNWJWMGN2ckZucC9VaEUwczV1cUNrPQ   gdrive-osx-x64   8.3 MB   2016-02-21 20:47:04   False
0B3X9GlR6EmbndVEwMlZCUldGWUlPb2lTS25rOFo1L2t6c2ZVPQ   gdrive-osx-x64   8.3 MB   2016-02-21 21:12:09   False
```
