### ISSUE TITLE
long uploads fail

### ISSUE THREAD

**Issue by idiomatic** [prasmussen/gdrive#20]
Uploads that take longer than 1 hour (due to file size or limited bandwidth, or both) result in:

    googleapi: Error 401: Invalid Credentials, authError

from code.google.com/p/google-api-go-client/drive/v2/drive-gen.go:3481, upon `googleapi.CheckResponse(res)`.

My assumption is that Google is testing the expired-during-transit access_key upon completion of the POST rather than at the beginning.

**Comment by igloosPat** [comment]
This has been fixed now. I reported about the fix last week by using uploadType=resumable (https://code.google.com/p/gdata-issues/issues/detail?id=5124 and https://code.google.com/p/google-api-python-client/issues/detail?id=231) and I successfully uploaded a big file on the new version 1.5.0.

**Comment by prasmussen** [comment]
Thanks @igloosPat :)
