### ISSUE TITLE
Subfolders?

### ISSUE THREAD

**Issue by willemdh** [prasmussen/gdrive#204]
Hello,

Thanks for this very useful project. I have a question I can't find the answer for on your readme.

How do I create a subfolder? Tried `gdrive mkdir Backups/test` but it creates `Backups_test` folder.

Thanks a lot!

Willem

**Comment by saivert** [comment]
You would have to do that in two steps currently.

gdrive mkdir Backups
This will return the id of the Backups folder to you. Next:
gdrive mkdir --parent <id of Backups folder> test

**Comment by willemdh** [comment]
Thanks for your answer!
