### ISSUE TITLE
Can't reconnect after revoking from GDrive apps

### ISSUE THREAD

**Issue by lucascrezende** [prasmussen/gdrive#212]
I installed everything and it worked fine. Then I checked how to revoke the access, but now I can't reconnect. When I run the `gdrive list` command in order to see the URL and get the token, what I get is: 

```
C:\Users\Lucas Rezende>gdrive list
Failed to list files: googleapi: Error 401: Invalid Credentials, authError
```

I already tried deleting and reinstalling GDrive binaries but I get the same error.

How can I make this work again?

Thanks in advance.

**Comment by beresnyak** [comment]
this is also mentioned here: #210 
on linux manually delete ~/.gdrive/*.json 
on Windows -- find the application configuration folder and do the same

**Comment by lucascrezende** [comment]
@beresnyak Thank you for the reply. I tried to look it up but haven't found it.
