### ISSUE TITLE
Ultimate performance. But one great drawback...

### ISSUE THREAD

**Issue by ChandraNakka** [prasmussen/gdrive#22]
Dear developer,

This is very useful for all platform developers.

But progress bar is not found for download/upload.

Please provide this feature.

It's awesome work. Keep it up....

**Comment by limoragni** [comment]
+1 to the progress bar or some percentage indicating that things are getting uploaded!

**Comment by pimlottc** [comment]
Agree, getting some feedback when transferring a multi-gig file would be much appreciated.

**Comment by prasmussen** [comment]
Basic progress bar is enabled by default for larger files in gdrive 2.
