### ISSUE TITLE
Authentification needed without opened session on Windows

### ISSUE THREAD

**Issue by ordimans** [prasmussen/gdrive#239]
Hello

I have a schedule task on Windows XP, it synchronize a file on my Gdrive.
No problem if i opened a session and execute the task.
But when there is any session, the task start and when Gdrive upload, it ask the verification code.
I have the .gdrive folder in the user older who execute the task.
For example, my task must start with TOTO user, and in TOTO home folder/applicationData, i have .gdrive.

Do you have an idea ?

Can I force the folder of the token ?

regards

**Comment by ordimans** [comment]
Any idea ?

**Comment by tleskin** [comment]
@ordimans We're having the same issue and haven't gotten it to work yet either.

**Comment by ordimans** [comment]
I change my command line with
`drive --refresh-token AUTH_TOKEN` 

It seems to be OK, i will confirm in some days, if no problem encountered.

**Comment by ordimans** [comment]
Work without problem since several month.
Issues can be closed.
