### ISSUE TITLE
"gdrive about" results in error

### ISSUE THREAD

**Issue by hemantcompiler** [prasmussen/gdrive#257]
This is the error that I got,
`Failed getting oauth client: Failed to read token: unexpected end of JSON input`

Also .gdrive folder is not created in the home directory.

I am using "Ubuntu 16.04.1 LTS (GNU/Linux 4.4.0-62-generic x86_64)"

**Comment by aryabhatt** [comment]
I am getting the same error.

**Comment by EmmaSimon** [comment]
I was getting the same error, you can fix it with the patch from saaros's pull request until the devs accept it.
