### ISSUE TITLE
Service account problem

### ISSUE THREAD

**Issue by demonguy** [prasmussen/gdrive#259]
I'm not sure if i should ask this question here, but i'm confused.
I successfully create a service-account used by gdrive, but i found it's a different drive that i have on drive.google.com. 

For example, i create a service-account with Gmail-A, and then log into drive.google.com with Gmail-A, their contents are different

How to access the original one using service-account?

**Comment by asmith20002** [comment]
Service accounts are separate accounts. That's why you're seeing different content.

Your fastest shortcut is to give permission to your Service accounts for those files/folders you have in mind.

**Comment by demonguy** [comment]
I see. Thanks. And sorry for asking such noob question
