### ISSUE TITLE
.gitignore clash

### ISSUE THREAD

**Issue by mikecarr** [prasmussen/gdrive#276]
In one of the folders I want to sync I have a tmp folder that I do not want sync'd, I added tmp/ to .driveignore, when I run the command I get the following:

'/timelapse/tmp' is set to be ignored yet is being processed. Use `force` to override this
ERROR - gdrive Processing failed.

How can I get around this?

drive version: 0.3.8

**Comment by mikecarr** [comment]
wrong application, sorry

**Comment by virgilioUEG** [comment]
https://github.com/prasmussen/gdrive/issues/448


is .gdriveignore on the root folder to sync. only on root folder.
