### ISSUE TITLE
how to switch account?

### ISSUE THREAD

**Issue by lowprofileusername** [prasmussen/gdrive#299]
I would like to upload file to different account? what's the command for logout and auth again with a new account?

**Comment by y3nd** [comment]
So how you did this ?

**Comment by subrahmanyamags** [comment]
did anyone do this yet?

**Comment by subrahmanyamags** [comment]
below will allow you to reconfigure the user id.
gdrive --config . list

**Comment by biplobsd** [comment]
https://github.com/gdrive-org/gdrive/issues/410#issuecomment-435638922
Remove account data to get logout.

**Comment by shrikant2002** [comment]
> below will allow you to reconfigure the user id.
> gdrive --config . list

this is not working in windows gdrive exe

**Comment by mattgilbertnet** [comment]
> [#410 (comment)](https://github.com/prasmussen/gdrive/issues/410#issuecomment-435638922)
> Remove account data to get logout.

This worked for me. On a mac, this is simply 

1. `rm ~/.gdrive/token_v2.json` 
2. then `gdrive about` to log back in.

**Comment by mbahgatTech** [comment]
For  anyone still struggling with this on windows: Your .gdrive folder should be in this path `C:\Users\<user>\AppData\Roaming`, delete token_v2.json then run `gdrive about` will prompt you for a verification code and a link that you can open from the new account.
