### ISSUE TITLE
Download all files in a folder

### ISSUE THREAD

**Issue by garygreen** [prasmussen/gdrive#30]
Currently possible?

**Comment by oroce** [comment]
Oh I needed the same thing, this is how I solved it:
~~~
drive-darwin-amd64 list -n --query "'<folder_id>' in parents" | awk '{print $1}' | xargs -I {} sh -c 'drive-darwin-amd64 download --id {}'
~~~

**Comment by kaimast** [comment]
What about folder with subfolders? Why can't I just download the folder with all its content?

**Comment by oroce** [comment]
I'm not sure whether it's possible through the API, but you can check it yourself.

I'm using a recursive bash script to download all the files. If you are interested i can share but im on mobile atm

**Comment by rbeede** [comment]
I know the Google Drive UI lets you download a folder.   It is zipping the contents and any sub-folders and providing a single zip download.   I'm not sure if the API has a call for that or not.

**Comment by xezpeleta** [comment]
+1

**Comment by xrobin** [comment]
@oroce it would be very useful if you could share the script. Detecting if a file is in fact a folder doesn't seem very trivial (`0.0 B` seems to be a hint but not fool-proof, one need to call `drive info` on the file and look for an Md5sum, missing on folders).

Ultimately one could think of a `-r` (`--recursive`) argument on `download` that would do it automatically.

**Comment by rbeede** [comment]
What about the following property:

https://developers.google.com/drive/v2/reference/files#resource

folderColorRgb - Folder color as an RGB hex string if the file is a folder. The list of supported colors is available in the folderColorPalette field of the About resource. If an unsupported color is specified, it will be changed to the closest color in the palette.


Also folders used to be called labels.   Not sure if that helps with the API.

**Comment by oroce** [comment]
@xrobin 
here we go:

```
#!/bin/bash
IFS=$'\n'

files=()

recurse() {
  id=$1
  echo "query '$id' in parents"
  files=$(drive-darwin-amd64 list -n -m 1000 --query "'$id' in parents")
  for file in $files
  do
    # id<whitespace>name<whitespace>size
    # splitting things
    id=$(awk '{print $1}' <<< $file | sed -e 's/ //g')
    id=${id:0,1} #substring

    name=$(awk '{print $2}' <<< $file)
    size=$(awk '{print $3}' <<< $file)
    
    # ops it's a directory
    if [ "$size" == "0.0" ];
    then
      echo "recurse on $name\n"
      recurse $id
      continue
    fi
   
    files+=("$id;$name")
  done
}
recurse '<google drive folder id>'

printf "Found %s files\n" "${#files[@]}"
```

What it does, it runs through a folder and finds all the files and puts into `files` array as a semicolon separated value.

**Comment by prasmussen** [comment]
gdrive 2 supports recursive download: `gdrive download -r <id>`

**Comment by tukusejssirs** [comment]
@prasmussen, I just used it, but not all dirs and files were downloaded. This is the command I ran:

`../gdrive-linux-x64 download -r [dir-id]`

Here is the list of dirs and files of the particular dir I tried to download:
```bash
texty  # dir
spevniky  # dir
noty  # dir
akordy  # dir
readme  # google document → this is the only gDocument in the dir and its subdirs
                          # and is not important at all
```

And these are dirs actually downloaded:

```bash
spevniky
text
```

And even in `spevniky` subdir, no all dirs and files were downloaded.

All I want is to download all dirs and files recursively from gDrive’s folder.

As a side note, the size of the downloaded files is 1.1 GiB (1091908 kiB). I also tried to download the dir using gDrive website, but I failed, too, to download all files and dirs (this is the reason I tried your program).
