### ISSUE TITLE
Environment variable for alternative config directory

### ISSUE THREAD

**Issue by rafi** [prasmussen/gdrive#31]
Instead of aliasing gdrive, _e.g._
```bash
alias gdrive="gdrive -c $XDG_CONFIG_HOME/gdrive"
```

It'll be nicer to have an environment variable to do that, _e.g._
```bash
export GDRIVE_CONFIG_DIR="$XDG_CONFIG_HOME/gdrive"
```

**Comment by prasmussen** [comment]
GDRIVE_CONFIG_DIR environment var is available in gdrive 2.
