### ISSUE TITLE
Change access token.

### ISSUE THREAD

**Issue by C10udburst** [prasmussen/gdrive#317]
I Am using Windows. I Connected Gdrive using token and now I removed that connection and I don't have that token. Now I get an error:
`Failed to get file: googleapi: Error 401: Invalid Credentials, authError`
How can I reset this to obtain new token?

**Comment by ewwink** [comment]
delete `%appdata%\.gdrive\token_v2.json`

**Comment by SwistakPL** [comment]
Thx
