### ISSUE TITLE
Add OCR support

### ISSUE THREAD

**Issue by p2baron** [prasmussen/gdrive#34]
Great tool! Thanks for making this.
Can you add the option to enable OCR on a file upload?

**Comment by MarkKropf** [comment]
Looks like there is already upstream support in the api library maintained by the same author as this cli. 

https://github.com/prasmussen/google-api-go-client/blob/master/drive/v2/drive-gen.go#L3193-3205

Should just be adding the argument to the CLI in this repo.

**Comment by MarkKropf** [comment]
Ok, looks like this functionality may be disabled now. I noticed that the gdrive web ui no longer allows this option to be set. The API still receives the call, but the test PDF I uploaded did not get ocr'd. 

It appears the new mode they are pushing for is for folks to use the 'convert' option instead for anything needing ocr.

If anyone else has found that this feature is still active the api, let me know.
