### ISSUE TITLE
upload folder, some files are missing

### ISSUE THREAD

**Issue by albaldi** [prasmussen/gdrive#35]
I just uploaded a folder with
`gdrive-cli upload -f name\ folder/ -p 0123456789abcdef`

Of the 7 files in folder, 2 are missing.
Is there a way to understand why? A log file, a verbose mode?

thanks

**Comment by DrStuartMcIntyre** [comment]
I also had this, but the files would spontaneously appear after a while. May be an issue with GDrive itself? http://stackoverflow.com/questions/13010191/uploaded-file-sometimes-doesnt-appear-on-the-google-drive-web-page

**Comment by Drezzler** [comment]
I can confirm , this is an issue with google drive itself , not gdrive.
