### ISSUE TITLE
Unable to click on circle element javascript

### ISSUE THREAD

**Issue by karunasaxena** [prasmussen/gdrive#358]
Can anyone please let me know how can I click on circle element of a map using javascript

URL for reference
http://lacontroller.maps.arcgis.com/apps/View/index.html?appid=cc0bc0590a18479ab89e0c102860d345&extent=-122.1079,31.6761,-114.6042,34.4334

**Comment by chuanzgh** [comment]
Pretty sure gdrive can't help do what you wanted to do.

**Comment by karunasaxena** [comment]
Sorry about that
