### ISSUE TITLE
gdrive doesn't show Google Docs

### ISSUE THREAD

**Issue by lmmx** [prasmussen/gdrive#36]
`drive list -nq "'$fileid' in parents"`

where `$fileid` is the ID of a folder containing `.gdoc` (Google Docs) files and child folders only shows the child folders.

Listing the contents of one of the child folders shows the PDFs it contains, so it seems like `.gdoc` files aren't visible using this tool?

Very annoying as Google Drive has begun converting all notes from .gdoc to .docx upon zip download, with no option to turn off conversion as for uploads :disappointed: 

**Edit:** Notes on [my solution to the latter problem are here](https://github.com/lmmx/devnotes/wiki/Writing-.gdoc-files-from-a-web-browser) (though still unclear why this tool can't make the process easier)

**Comment by djm68** [comment]
This issue is preventing gdrive from being much more useful.  I can use gdrive to upload and text document, I can then download the same document.  However, if I open the uploaded document in google docs, it is converted to google doc format which is then no longer visible to gdrive.

**Comment by monperrus** [comment]
+1

I'd like to use gdrive to backup my Google Documents. Is it possible?

**Comment by lmmx** [comment]
@monperrus The Google Docs `.gdoc` format is totally minimal, [just containing the URL](https://github.com/lmmx/devnotes/wiki/Writing-.gdoc-files-from-a-web-browser) in plain text basically. "Backing them up" therefore doesn't really have much meaning.

I've given up the thought of using gdrive for this (it's generally quite buggy), but you may be interested in backing up Docs as markdown - I currently do this just to work with Docs in drafting.

See [this repo](https://github.com/lmmx/gdocs2md-html/), a tool I've modified that converts Docs to markdown and HTML

**Comment by monperrus** [comment]
@lmmx I've rolled my own Python script for backing up my Google Documents: <https://github.com/monperrus/dl-gdocs>

**Comment by lmmx** [comment]
Oh, neat! I always found the conversion butchers my document, whereas the markdown generation is nicely programmatic and you can work around formatting bugs, but great that it's an option now, nice work! :+1:

**Comment by monperrus** [comment]
If you want to add a listing of Google Documents in gdrive, the request
to be done is `mimeType=application/vnd.google-apps.document` (resp.
`application/vnd.google-apps.spreadsheet` and
`application/vnd.google-apps.presentation`).

(note that `mimeType contains google-apps.document` does not answer
anything.

**Comment by quinncomendant** [comment]
`gdrive list -q "mimeType = 'application/vnd.google-apps.spreadsheet'"` returns only two items, out of about fifty spreadsheets I have in my account. `gdrive list -q "mimeType = 'application/vnd.google-apps.document'"` returns nothing, despite many documents existing. Any ideas why this query isn't able to retrieve the full list of documents?

**Comment by prasmussen** [comment]
In 1.7.0 there is a new flag --include-docs that will include google docs in the listing and a --format flag to download a google doc in a specified format.

**Comment by quinncomendant** [comment]
😍
