### ISSUE TITLE
Does gdrive not work running from cron?

### ISSUE THREAD

**Issue by crobertwatson** [prasmussen/gdrive#360]
I created and tested a bash script to upload files to gdrive and it was all working fine. Then I put it into a crontab and everything in the script worked except the gdrive command. 

`gdrive sync upload --keep-local --delete-extraneous . $GDRIVEFOLDERID`

What I got from that was 

`gdrive: command not found`

I was running this as the admin user on a Mac. `which gdrive` says it's at `/usr/local/bin/gdrive`. Is there something special I'd need to do in my bash script to ensure gdrive is able to run as part of a cron? I tried being more specific with gdrive's path...

`/usr/local/bin/gdrive sync upload --keep-local --delete-extraneous . $GDRIVEFOLDERID`

But that didn't help either.

**Comment by crobertwatson** [comment]
Never mind. It was a path problem with the crontab. I added proper paths and got it working.

**Comment by liuyigh** [comment]
Please close this issue. :)
