### ISSUE TITLE
Directory upload is not recursive

### ISSUE THREAD

**Issue by pgcd** [prasmussen/gdrive#37]
I suppose this is a deliberate choice, but the fact that uploading a directory only uploads the files in it (and not the subdirectories) is rather inconvenient - especially since it's not made clear. 
Ideally, there should be a recursive mode but, failing that, I think that the behavior should be explicit.

**Comment by tanc** [comment]
Agreed, this just burnt me. Took ages to figure out what was happening.

**Comment by vtraag** [comment]
Same for me here, took me a while to figure out. A recursive mode would be much appreciated.

**Comment by prasmussen** [comment]
Recursive upload has been added in 1.4.0.

**Comment by tanc** [comment]
Great! Will try this out soon.

**Comment by pgcd** [comment]
Brilliant!
