### ISSUE TITLE
Pipe from gpg to gdrive?

### ISSUE THREAD

**Issue by herohamp** [prasmussen/gdrive#378]
Is it possible for me to pipe from gpg to gdrive directly?

**Comment by mbenlioglu** [comment]
You can pipe them like any command

From local to drive:

    $ gpg -eu sender.mail@gmail.com -r reciever@foo.bar --output - hello.txt | gdrive upload - hello.txt.gpg
    Uploading hello.txt.gpg
    Uploaded 6fMRq3Cb3xAEztmJiwzB7jnvGUWCFg9al at 425.0 B/s, total 472.0 B

From drive to local:

    $ gdrive download --stdout 6fMRq3Cb3xAEztmJiwzB7jnvGUWCFg9al | gpg --batch --quiet --passphrase "passwdOfYourKey"  -d - > hello.txt

**Comment by herohamp** [comment]
Thank you <3

**Comment by mbenlioglu** [comment]
You're welcome ;)
