### ISSUE TITLE
Max list at 460

### ISSUE THREAD

**Issue by batteryshark** [prasmussen/gdrive#38]
For some reason, running list while querying against a parent ID (listing all files in that directory) even with a -m for max return value only returns 460 file entries... anything lower than 460 works properly, but nothing seems to work past it.

**Comment by batteryshark** [comment]
This is apparently a pretty common thing in a lot of gdrive programs. I wrote a python script as a workaround to pull all the file ids in a directory and pass that to this program; the issue appears to come from not fully polling all the pages of results when calling list()

**Comment by prasmussen** [comment]
Was fixed some time ago.
