### ISSUE TITLE
"-m 1" not working

### ISSUE THREAD

**Issue by tinamore** [prasmussen/gdrive#43]
Hi prasmussen
I query list normal is success but add -m 1 (to get first item) then is not result
--------------------------
C:\Windows\system32>gdrive list -q "title contains 'full'"
Id                             Title                                      Size     Created
0BxRXe4e5tCA0SlZNNWtnUEtJRUU   FULL-(local)-smart_...0150225_030000.sqb   507 MB   2015-02-25 03:02:15
0BxRXe4e5tCA0ZGdpTGNhSkJCWTA   FULL-(local)-smart_...0150224_030000.sqb   506 MB   2015-02-24 03:02:16
0BxRXe4e5tCA0dmFZZjlZdlljc2s   FULL-(local)-smart_...0150223_030000.sqb   504 MB   2015-02-23 03:02:08
0BxRXe4e5tCA0SXlLcFZPU0huT1k   FULL-(local)-smart_...0150222_030000.sqb   503 MB   2015-02-22 03:02:17
0BxRXe4e5tCA0M2VvMWp1WnJSQ0U   FULL-(local)-smart_...0150221_030000.sqb   502 MB   2015-02-21 03:02:07
0BxRXe4e5tCA0TG1RNjNvZV9PNE0   FULL-(local)-smart_...0150220_030000.sqb   501 MB   2015-02-20 03:01:59
0BxRXe4e5tCA0M0d5djZtaEZkMFE   FULL-(local)-smart_...0150219_030000.sqb   500 MB   2015-02-19 03:03:04
0BxRXe4e5tCA0eW8xU0lwbGRfRkU   FULL-(local)-smart_...0150217_030000.sqb   499 MB   2015-02-17 03:01:56

C:\Windows\system32>gdrive list -q "title contains 'full'" -m 1
Id   Title   Size   Created

C:\Windows\system32>
-----------
please fix error
Thanks. Your tools are very excellent work backup. I love your gdrive tool.

**Comment by prasmussen** [comment]
This has been fixed in gdrive 2.
