### ISSUE TITLE
``Error 403: Rate Limit Exceeded'' at ``self.service.Files.List().''

### ISSUE THREAD

**Issue by SaitouToshihide** [prasmussen/gdrive#430]
This happens frequently when ``sync upload''ing a folder with a large number of files.

  Failed listing files: googleapi: Error 403: Rate Limit Exceeded, rateLimitExceeded

The location of this error is the below in the list.go:

    err := self.service.Files.List().Q(args.query).Fields(args.fields...).OrderBy(args.sortOrder).PageSize(pageSize).Pages(context.TODO(), func(fl *drive.FileList) error {

How can we rewrite this query to eliminate the rate limit?
Does using the pageToken mitigate the rate?

**Comment by chunglim** [comment]
* SaitouToshihide (notifications@github.com) wrote:
> This happens frequently when ``sync upload''ing a folder with a large number
> of files.
But many times, I uploaded only a few files I got the same error.

-- 
Gua Chung Lim
 
"UNIX is basically a simple operating system,
but you have to be a genius to understand the simplicity."
-- Dennis M. Ritchie

**Comment by TA40** [comment]
Also don't use the public API from the creator of gdrive. Look here: https://github.com/prasmussen/gdrive/issues/426 or here https://github.com/prasmussen/gdrive/issues/426#issuecomment-459150627

**Comment by SaitouToshihide** [comment]
It seems that the problem soleved by changing ClientId/ClientSecret.

Thank you.

(In this process, syncable directories became not-syncable.  Maybe bacause an application is identified by ClientId and AppProperties' syncRoot stored for each ClientId.  It is safe but cause such problem.  So how about chage AppProperties and syncRootId with Properties and URI for all forked gdrive descendant?)

**Comment by TA40** [comment]
It didn't work because the API gets overflooded with requests
