### ISSUE TITLE
Error uploading big files

### ISSUE THREAD

**Issue by erpalma** [prasmussen/gdrive#46]
Uploading a big file (>20GB) to my Drive lead me to this error:

An error occurred uploading the document: Post https://www.googleapis.com/upload/drive/v2/files?alt=json&convert=false&uploadType=resumable&upload_id=CUT: dial tcp: lookup www.googleapis.com on 8.8.8.8:53: dial udp 8.8.8.8:53: too many open files

I have enough free space to upload the file and I use version 1.5.1 on ubuntu 14.04 amd64.

P.S. Am I the only one having lower uploading speed with latest version? ~1-2MB/s on a 100Mbit network.

**Comment by rdeavila** [comment]
:+1:

**Comment by bxshi** [comment]
I also have problem when uploading moderate large files (around 1GB), the error I get is 

```
An error occurred uploading the document: Post https://www.googleapis.com/upload/drive/v2/files?alt=json&convert=false&uploadType=resumable&upload_id=AEnB2Urh1F-ybIYsMrE616kFv5rrmKEZLAN2NH2UI-f8FH7mOJRRYlSdit3xCYJrtZpaqPw7assXLSg96_GTLqN3aXXAzvKiYw: dial tcp 216.58.216.234:443: i/o timeout
```
My uploading speed is also 1MB/s.

**Comment by erpalma** [comment]
With bigger chunks of ver 1.6.1 the problem seems to be fixed

**Comment by alexjj** [comment]
On my FreeBSD machine I have no issue but on my Linux box I get this error when uploading a ~1GB file. I just installed the latest 64bit build.

**Comment by DarkLinkXXXX** [comment]
I am also having this issue.

**Comment by Drezzler** [comment]
And me too , started happening only recently , I am guessing this a server issue with limited disk I/O being unable to send the data fast enough and a low disk I/O ofc which is leading to uploads getting stalled and eventually failing ..

**Comment by prasmussen** [comment]
Try gdrive 2 if this is still a problem.
