### ISSUE TITLE
Can Order by Name or modifiedDate ?

### ISSUE THREAD

**Issue by tinamore** [prasmussen/gdrive#47]
Hi there.
Default List return the file list sorted by modifiedDate
I can list with sort Order by Name?
Thanks

**Comment by johnr14** [comment]
For date sort : 
./gdrive list | sed "1 d" | sort -n -k 5,5

For name sort
./gdrive list | sed "1 d" | sort -k 2,5

For size 
Doesn't work as mixed type of unit .. B, KB, MB...

**Comment by prasmussen** [comment]
You can use the `--order` flag with gdrive 2:
```
gdrive list --order "name asc"
gdrive list --order "modifiedTime desc"
```
