### ISSUE TITLE
Long uploads fail when using stdin

### ISSUE THREAD

**Issue by NeoXiD** [prasmussen/gdrive#48]
Basically, I'm facing the same issue as in #20. As I can clearly see within the last commit, the bugfix doesn't apply to stdin and only helps when directly specifying large files. As I need both a progress bar and some ratelimiting, I've created a bashscript which recursively uploads whole directories including all files. Also, I've implemented MD5 checksumming, so that those files won't get reuploaded.

The way I'm calling this application is like that: `cat largefile | pv -pteraT -L <ratelimit> -s <totalfilesize> | ./gdrive upload -s -t <filename> -p <folderid>`. After quiet a few hours of uploading, it failed with "Error 401: Invalid credentials" as listed above. Could that fix also get implemented for uploading via stdin?

**Comment by prasmussen** [comment]
Resumable uploads requires the size of the file up-front, thats why its not used when uploading via stdin, as I have no way of knowing the size.
I see that `pv` takes the filesize in as an argument, that could be a solution for gdrive as well. What do you think?

**Comment by NeoXiD** [comment]
I already expected that when I took a glance at the sourcecode, but I wasn't sure. I think it would be a great idea to do it similar like `pv` - if no size is specified, upload it non-resumable (and maybe print a warning/hint?), if a size got specified, use the resumable way of doing it.

**Comment by prasmussen** [comment]
Agreed

**Comment by NeoXiD** [comment]
I'll make a push request for that feature soon, stay tuned.

**Comment by NeoXiD** [comment]
Just a short ping @prasmussen, as I'm not sure if you'll get a notification about my EDIT or not. I'll possibly try later on to go that quick'n'dirty way - it would work for me but ofcourse isn't a proper solution.

**Comment by prasmussen** [comment]
Oh, thats too bad.
I haven't followed the code to see what happens to the Reader, so i don't really have any other ideas at the moment. Im guessing seeking is required when resuming an upload -- I'm not sure why you get a seek when doing a normal upload though.
If you get the wrapper to work and it seems reliable, I will accept the pull request and I could mark it as an experimental feature or something.

**Comment by NeoXiD** [comment]
Short update: I've successfully uploaded now multiple big files (several GB) during the last three days and some of them took over 10 hours. My wrapper class works fine - I just have to add some additional code so that mime type detection works, I've disabled that currently and always use "application/octet-stream". Otherwise than that, the solution works way better than I've expected - PR coming soon.

**Comment by prasmussen** [comment]
Sounds promising :)

**Comment by prasmussen** [comment]
[ResumableMedia](https://godoc.org/google.golang.org/api/drive/v3#FilesCreateCall.ResumableMedia) has been deprecated in google-api-go-client and the problem with long uploads failing with [Media](https://godoc.org/google.golang.org/api/drive/v3#FilesCreateCall.Media) seems to be fixed according to my tests with gdrive 2.

```bash
$ cat video.mp4 | pv -q -L 50k | gdrive upload - video.mp4
Uploading video.mp4
Uploaded 0B3X9GlR6EmbnSFRwSTNMZkY3Nzg at 51.2 KB/s, total 1.8 GB
pv -q -L 50k  21.88s user 18.02s system 0% cpu 10:00:43.71 total
```
