### ISSUE TITLE
Upload speed issue

### ISSUE THREAD

**Issue by cnbeining** [prasmussen/gdrive#49]
I've noticed several people here are having speed issue.

For me, I am using a VPS, which comes with at least 200MiB/s upload speed, and great peering with Google.

But my speed is kinds of limited to 1~1.5MiB/s.

Any idea what caused such problem?

@erpalma
@bxshi

**Comment by bxshi** [comment]
I'm using internet2 which should be super fast...

Unfortunately I do not know `Go` at all, so I have no idea about the cause of this problem...

**Comment by cnbeining** [comment]
Gotcha.

![image](https://cloud.githubusercontent.com/assets/1560962/6762835/0a548dfc-cf3e-11e4-9c72-8fe19ec6099d.png)

To make upload resumable, @prasmussen used "resumable upload" here, which is good.

In the SDK, it is required that the **minimum** chunk size is 256*1024 = 256K. 

If the network is not stable, this is good; however, for most home users, especially for server users(whose peering is great and link is so stable that it has a SLA), **256K is too mild**.

I am trying to find the place where the chunk size is determined, but I do not know golang...

It would be better if this size is set larger(say, 5MiB), and adjustable with command line or config file.

FYI.

**Comment by prasmussen** [comment]
Good catch @cnbeining.
The chunk size seems to be defined here: https://github.com/google/google-api-go-client/blob/master/googleapi/googleapi.go#L303
I will experiment a bit the value to see if it helps the upload speed.

**Comment by prasmussen** [comment]
There is definitively an improvement.
At 2^19 bytes i don't see any great speed boost, but at 2^20 i more or less max my 50mbit connection.
I think I will set 2^20 as the default and add a command line flag as @cnbeining suggested, to override the value if needed.

**Comment by cnbeining** [comment]
I am so glad that I helped a little bit :smile: 

I suppose we can tolerate a chunk size as (Normal_Home_Bandwidth_Expected_Upload_Speed) * 5 sec. 

For whose network is not stable(e.g., 3G signal in a fast moving car), it would not make their life more comfortable even reduce the chunk to minimum size; And for server hosted in datacenters, they can dump 20MiB of data every second to Google without any package lost...

**Comment by bxshi** [comment]
I would appreciate if you can provide a new compiled version with a higher `chunkSize` by any chance.

**Comment by prasmussen** [comment]
Version 1.6.0 has a default chunk size of 2^20 bytes (1MiB) and can be changed with the -C flag.

**Comment by cnbeining** [comment]
Thank you very much!

Just to let you know that the chunk size must be times of 256KiB.

**Comment by cnbeining** [comment]
FYI:

For lazy people:

Throw this into your .bashrc:

```
function gdupload() { 
  drive upload -C 52428800 -f $1
}
```

Save a tiny bit of work.
