### ISSUE TITLE
Space used and space left

### ISSUE THREAD

**Issue by johnr14** [prasmussen/gdrive#51]
Hi, could you add a command to return spaced used, free space, total space of the google drive ?

It would be great to add a check space left before uploading a large file, 
or specify a min_free_space=500mb
so an upload doesn't fill all the space left ... because emails will bounce back if no more space.

P.S.
It would be usefull to have all filesize return in bytes with 
list -b and info -b

Thanks and great work !

**Comment by prasmussen** [comment]
I've added the `drive quota` command in 1.8.0 which will print out free space, etc. I've also added a `--bytes` flag to info, list and quota to force size in bytes.
I wont be implementing the min_free_space logic at this time, but it should be possible to write a wrapper script now that checks for free space before uploading.
