### ISSUE TITLE
username / password for login?

### ISSUE THREAD

**Issue by jayjupdhig** [prasmussen/gdrive#518]
how to set?

thx for feedback,
jan

**Comment by mxdpeep** [comment]
move to RClone project, GDrive Crossed the Jordan, it's dead 💀
https://rclone.org/

**Comment by mbrother2** [comment]
@all

Try to use my script to build gdrive with your own Google credential: https://github.com/mbrother2/backuptogoogle
Or work with rclone: https://github.com/mbrother2/butdr

**Comment by jayjupdhig** [comment]
ok thx
