### ISSUE TITLE
File revision

### ISSUE THREAD

**Issue by johnr14** [prasmussen/gdrive#52]
Google drive provides file revision for up to 30 days,
could gdrive access those information and allow reverting to an older version ?

Also, if uploading a file with same name in the same directory, overwrite the old one instead of creating a new file.

Thanks

**Comment by DerSeegler** [comment]
Would also love to have the feature that a file gets updated instead of created when there already is a file with the exact name. I'm using this tool to backup some data. Using Google Drives revision service would be amazing for this. Any chance this gets implemented?

**Comment by berna1995** [comment]
Yeah, it would be amazing.

**Comment by fnkr** [comment]
+1

**Comment by alpi-ua** [comment]
I hope i will see this in gdrive.

**Comment by prasmussen** [comment]
gdrive 2 has the `update` command which will create a new revision of a single file. gdrive 2 also has some new sync commands that can be used to update multiple changed files. Readme contains an example.

**Comment by DerSeegler** [comment]
Thank you so much for this. It works perfectly. Is there any way I can donate to you because I would really like to.
