### ISSUE TITLE
cron job configuration

### ISSUE THREAD

**Issue by jmrezayi2** [prasmussen/gdrive#55]
Hello!

Thank you for this project. I have a problem, I am able to use the drive in a shell script, however when I set it as a cron job for the same user, it fails.

I have tried with custom config file and no changes..

Do you know how I might be able to debug it?
Thanks!

**Comment by markodudic** [comment]
I have same problem with crone. Do you find a solution?

**Comment by rdeavila** [comment]
You're calling the binary using the full path? I had this problem, because the cron `PATH` is different from the terminal `PATH`. Calling the executable using the full path (in my case `/usr/local/bin/drive`) solved the problem.

**Comment by jmrezayi2** [comment]
Well I think I am.. I have the drive in a shell script (called backp.sh). 

summary of backup.sh:
****************************
I use the following variable to get the absolute path and use absolute path everywhere:
SCRIPTPATH=$(cd" $( dirname "$0" )" && pwd)

then I am using such line in the shell:

drive --config $SCRIPTPATH/ -f $SCRIPTPATH/name.zip 
****************************
Then in my crontab I am using this line:

sh /home/some path/backup.sh>>/home/some path/log.txt

it does all the steps but fails to upload to google drive. I tried specifying the credentials by config but it is not working. needless to say the  "sh /home/some path/backup.sh>>/home/some path/log.txt" runs perfectly from anywhere..

Do you mean instead of typing drive -f somefile, I should call it with the full path?

Thanks

**Comment by chuanzgh** [comment]
Maybe you can try importing your account profile at the start of your
script. depending on your shell, it's something like:
. ~/.profile

This little line can solve the mystery sometimes.

**Comment by jmrezayi2** [comment]
Still no luck...
Just to be clear, I am using something like this in the shell script that is being called from crontab:

drive -f somefile.

Do you think I need to use it with the full path to the bin of drive?

Thanks all!

**Comment by markodudic** [comment]
I use full path as rdeavila suggest and it works for me.

**Comment by jmrezayi2** [comment]
can you clarify more please?

does it mean instead of calling drive -f somefile, you used /usr/local/bin/drive -f some file?

thanks

**Comment by rdeavila** [comment]
@jmrezayi2 I don't know if the question is for me, but... :smile: 

Yes. I'm calling the `drive` executable with the full path (`/usr/local/bin/drive -f some file`). I don't know if `/usr/local/bin` is the right place to install it, but that's the place I'm using now.

[Here is the AskUbuntu answer](http://askubuntu.com/a/23438) that helped me find the problem with cron.

**Comment by jmrezayi2** [comment]
@rdeavila  Thank you! you saved the day! You had the solution from the beginning and I did not understand it.

Thanks!
