### ISSUE TITLE
This app is temporarily blocked from logging in with your Google account

### ISSUE THREAD

**Issue by Envel-Nikita-Gutsenkov** [prasmussen/gdrive#564]
This app is temporarily blocked from logging in with your Google account

You can't log in to the app using your Google account because it hasn't passed our verification yet.

**Comment by ahmedselim2017** [comment]
Hi, how did you solve the issue? I am getting the same error.

**Comment by stilliard** [comment]
Ran into this issue earlier too, switching to service accounts resolved it for me. 
I did this a couple years ago too and made a post about it in case it helps anyone else running into this: https://blog.stapps.io/gdrive-backups-with-service-accounts/
