### ISSUE TITLE
where is the uploaded file

### ISSUE THREAD

**Issue by mlostekk** [prasmussen/gdrive#568]
I am wondering where the file is? I was uploading it and seeing it when i do „gdrive list“. But when i open my google drive in the browser, i cant find that file. Seems like its a different drive i am uploading. But where can i specify that? I thoughts its all setup in the https://console.developers.google.com/

I am using a service account as i want to connect it with my CI.

**Comment by mlostekk** [comment]
okay.. i found out that i am just uploadig to the service account gdrive, not to mie

**Comment by luis901101** [comment]
So there is no way to use --service-account to upload files to my own Google Drive and access files from https://drive.google.com/drive/my-drive ???

**Comment by luis901101** [comment]
I found out that I can share a folder from the Service Account's drive to any user like:

`gdrive --service-account my-service-credentials.json share --role writer --type user --email my-user@gmail.com FILE_OR_DIRECTORY_ID`

This way I can access files inside the Service Account drive

**Comment by Searge** [comment]
> I found out that I can share a folder from the Service Account's drive to any user like:
> 
> `gdrive --service-account my-service-credentials.json share --role writer --type user --email my-user@gmail.com FILE_OR_DIRECTORY_ID`
> 
> This way I can access files inside the Service Account drive

Thanks, so final ci would like like this:

```bash
gdrive --service-account $TOKEN upload $ARTIFACT -p $SHARED_FOLDER
```
