### ISSUE TITLE
Multiple Parents

### ISSUE THREAD

**Issue by shammishailaj** [prasmussen/gdrive#57]
Hi

I just started using your binaries and I find it to be great. Just wanted to know if there is a provision to make multiple parents of an object being uploaded. I read somewhere that google drive gives this feature

**Comment by prasmussen** [comment]
gdrive 2 lets you specify multiple parents:
`gdrive upload --parent 0B3X9GlR6EmbnR1pNR1FsRGR2bWs --parent 0B3X9GlR6EmbndHlqbWVxSi16WVE foo.txt`
