### ISSUE TITLE
Error when installing  go get github.com/prasmussen/gdrive

### ISSUE THREAD

**Issue by ismdcf** [prasmussen/gdrive#574]
I'm trying to install this tool via go 

my go version is 
```
go version 
go version go1.16 linux/amd64
```

I get the following error when running the command 

```
go get github.com/prasmussen/gdrive
go: downloading github.com/prasmussen/gdrive v0.0.0-20200728191437-31d0829c1807
go: downloading github.com/soniakeys/graph v0.0.0
go: downloading github.com/sabhiram/go-git-ignore v0.0.0-20201211210132-54b8a0bf510f
go: downloading golang.org/x/oauth2 v0.0.0-20210220000619-9bb904979d93
go: downloading golang.org/x/net v0.0.0-20210222171744-9060382bd457
go: downloading google.golang.org/api v0.40.0
go get: github.com/sabhiram/go-git-ignore@none updating to
	github.com/sabhiram/go-git-ignore@v0.0.0-20201211210132-54b8a0bf510f: parsing go.mod:
	module declares its path as: github.com/sabhiram/go-gitignore
	        but was required as: github.com/sabhiram/go-git-ignore


```

**Comment by CastBlacKing** [comment]
I'm with the same error.
`root@njosk:/usr/local/go# go get github.com/prasmussen/gdrive
go get: github.com/sabhiram/go-git-ignore@none updating to
        github.com/sabhiram/go-git-ignore@v0.0.0-20201211210132-54b8a0bf510f: parsing go.mod:
        module declares its path as: github.com/sabhiram/go-gitignore
                but was required as: github.com/sabhiram/go-git-ignore
root@njosk:/usr/local/go# `

**Comment by joshschriever** [comment]
I'm getting this same error. Likely caused by https://github.com/sabhiram/go-gitignore/commit/24b2447174be370e56ea86a72f00a76258606067, I think.

https://github.com/prasmussen/gdrive/pull/575 should fix it.
