### ISSUE TITLE
drive -a and drive -c

### ISSUE THREAD

**Issue by HappyHub1** [prasmussen/gdrive#58]
Hi. I was wondering how to use drive -a to change a google drive account.

drive -c doesn't seem to do anything but it may be because I have the wrong arguments.

**Comment by Lexmark0381** [comment]
Hi,
If you want to use a different account you could just delete the ".gdrive" folder in your home (~/.gdrive/).
If you want to manage more accounts at once, i do so, even if i think there are easier ways:
1)Configure first account (Account X): ~/.gdrive is created 
2) rename .gdrive in .gdriveAccountX
3)Configure second Account (Account Y): ~/.gdrive is created, now contains files about Account Y.

Now, when you have to use account X rename .gdrive in .gdriveAccountY and .gdriveAccountX in .gdrive.
When you want to use account Y rename .gdrive in .gdriveAccountX and .gdriveAccountY in .gdrive.

It's rude but it works.

**Comment by HappyHub1** [comment]
Thanks for the reply. I actually figured out the -c argument a few days ago. 
It is actually like this:  drive -c ./foobar upload --file file.mp4

When ./foobar doesn't exist, it will ask for a token. I believe this should be clarified in the --help section.

**Comment by prasmussen** [comment]
The readme now contains some more information regarding this under installation instructions.
