### ISSUE TITLE
 ./gdrive: No such file or directory

### ISSUE THREAD

**Issue by dhairya137** [prasmussen/gdrive#597]
I have extracted gdrive_2.1.1_linux_amd64.tar.gz on my ubuntu 20.04 but when I try to run gdrive with executable permissions I get this error.
![Screenshot from 2021-08-25 17-21-15](https://user-images.githubusercontent.com/40421470/130785691-2df794c0-e1a3-41a4-8300-c4d008b07a49.png)

**Comment by ma3yta** [comment]
You can use ``i386`` binary instead ``amd64``. It works fine for me.
```bash
wget -q -O /tmp/gdrive.tar.gz "https://github.com/prasmussen/gdrive/releases/download/2.1.1/gdrive_2.1.1_linux_386.tar.gz"
mkdir /tmp/gdrive && tar -xf /tmp/gdrive.tar.gz -C /tmp/gdrive
chmod +x /tmp/gdrive/gdrive
/tmp/gdrive/gdrive download 1o1qjRgkJtnF_8uGB1z6MRsQUjWinHUsw --recursive --path ~/Downloads

```

**Comment by RemiDesgrange** [comment]
(Possible reason) The doc say this program is statically linked, which is false on amd64 build . It depends on... musl, and not glibc, which is the default on many linux distro (including ubuntu, arch, etc...). Use the i386 build which is statically linked.

**Comment by sergeken** [comment]
I confirm that it needs musl, I had the same problem with Arch Linux

**Comment by t31k3** [comment]
`strings gdrive |egrep "[.]so$|[.]so[.]1"` 
yep: `sudo apt install musl`
`strace gdrive help` didnt help, but I think there is some command that let we see the dependencies other than force it thru `strings`

**Comment by RemiDesgrange** [comment]
`ldd ` is the command you are looking for I think.

**Comment by marhensa** [comment]
i spent near one hour to find this problem.
all those workaround always tell me to "chmod +x gdrive", which leads to nothing. 
THIS confirm my sanity, that indeed it's a real bug.

@ma3yta yes, thank you i386 binary works just fine. I temporarily using this, any downside compared to amd64?

**Comment by ma3yta** [comment]
@marhensa no downsides. the program just uses 32-bit (i386) CPU instructions instead of 64-bit (amd64) instructions which is OK for x86_64 processors.

**Comment by hiraksarkar** [comment]
I think we should keep the issue open, until readme atleast mentions this.

**Comment by ahmafi** [comment]
I have the same issue on 2.1.1

**Comment by pcstuff** [comment]
same issue

**Comment by wxthss82** [comment]
same issue

**Comment by duzhor** [comment]
```
root@localhost:~# gdrive about
-bash: /usr/local/bin/gdrive: No such file or directory
root@localhost:~# ldd gdrive
ldd: ./gdrive: No such file or directory
root@localhost:~# ldd /usr/local/bin/gdrive 
	linux-vdso.so.1 (0x00007ffcaacbe000)
	libc.musl-x86_64.so.1 => not found
root@localhost:~# 
root@localhost:~# apt install -y musl
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following NEW packages will be installed:
  musl
0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
Need to get 418 kB of archives.
After this operation, 800 kB of additional disk space will be used.
Get:1 http://deb.debian.org/debian bullseye/main amd64 musl amd64 1.2.2-1 [418 kB]
Fetched 418 kB in 0s (2947 kB/s)
Selecting previously unselected package musl:amd64.
(Reading database ... 30457 files and directories currently installed.)
Preparing to unpack .../musl_1.2.2-1_amd64.deb ...
Unpacking musl:amd64 (1.2.2-1) ...
Setting up musl:amd64 (1.2.2-1) ...
Processing triggers for man-db (2.9.4-2) ...
root@localhost:~# 
root@localhost:~# 
root@localhost:~# gdrive about
Authentication needed
Go to the following url in your browser:
```

**Comment by jonahpearl** [comment]
Confirm same issue, on a Linux 3.10 compute cluster. Musl didn't fix, using i386 seems fine.

**Comment by Delta-dev-99** [comment]
Confirm same issue on Ubuntu x86_64 machine Linux 5.15.0-46-generic
Installing musl (via `apt install musl`) fixed the issue
