### ISSUE TITLE
Failed to get file: googleapi: Error 404: File not found

### ISSUE THREAD

**Issue by kenorb** [prasmussen/gdrive#605]
```
$ gdrive download --recursive "https://drive.google.com/drive/folders/1zx8OX_Iq9NDwKh8RRBTuIrNTbpR9oi2H"
Failed to get file: googleapi: Error 404: File not found: https://drive.google.com/drive/folders/1zx8OX_Iq9NDwKh8RRBTuIrNTbpR9oi2H., notFound
```

**Comment by XiaoPanPanKevinPan** [comment]
According to the `gdrive help download`, the field after `[options]` should be `<fileId>`
In this case, it's `1zx8OX_Iq9NDwKh8RRBTuIrNTbpR9oi2H`

Which means, you should run it this way: `gdrive download --recursive "1zx8OX_Iq9NDwKh8RRBTuIrNTbpR9oi2H"`

**Comment by kenorb** [comment]
Thanks, it seems providing ID works fine.
