### ISSUE TITLE
How to install?

### ISSUE THREAD

**Issue by segatrade** [prasmussen/gdrive#608]
Ubuntu 20.04.3. I downloaded `gdrive_2.1.1_linux_amd64.tar.gz`. What's next?
I unpacked `tar xzf gdrive_2.1.1_linux_amd64.tar.gz` also but no install and cannot run. Not many info in Readme
`gdrive about`: `Command 'gdrive' not found`

https://askubuntu.com/questions/25961/how-do-i-install-a-tar-gz-or-tar-bz2-file didn't helped

**Comment by lan7ium** [comment]
Bonjour, tiens cadeau, j'ai eu le même soucis : https://github.com/prasmussen/gdrive/issues/580

**Comment by segatrade** [comment]
Merci @lan7ium
