### ISSUE TITLE
Don't launch after download last release bin

### ISSUE THREAD

**Issue by nkl90** [prasmussen/gdrive#617]
Hello! I am download a [last release of gdrive](https://github.com/prasmussen/gdrive/releases/download/2.1.1/gdrive_2.1.1_linux_amd64.tar.gz) for my arch:
```bash
nkl@nkl-adegara (11:15) ~ $ uname -a
Linux nkl-adegara 5.4.0-91-generic #102-Ubuntu SMP Fri Nov 5 16:31:28 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```
Try execute this, I get an error:
```
nkl@nkl-adegara (11:30) ~/Загрузки $ ./gdrive 
bash: ./gdrive: Нет такого файла или каталога
```
(No such file or directory)
Try run this:
```bash
nkl@nkl-adegara (11:30) ~/Загрузки $ ldd ./gdrive
	linux-vdso.so.1 (0x00007ffe9e18e000)
	libc.musl-x86_64.so.1 => not found
```
Why ready binary file needs any libraries??

**Comment by huww98** [comment]
It is weird. But gdrive_2.1.1_linux_386.tar.gz works on my x64 server.

See #580

**Comment by nkl90** [comment]
This is a clear amd64 build issue. Because bin from [gdrive_2.1.1_linux_386.tar.gz](https://github.com/prasmussen/gdrive/releases/download/2.1.1/gdrive_2.1.1_linux_386.tar.gz) work fine on my system:
```bash
nkl@nkl-adegara (09:36) ~/Загрузки $ ./gdrive_386 about
Authentication needed
Go to the following url in your browser:
https://accounts.google.com/o/oauth2/auth?access_type=offline&client_id=367116221053-7n0vf5akeru7on6o2fjinrecpdoe99eg.apps.googleusercontent.com&redirect_uri=urn%3Aietf%3Awg%3Aoauth%3A2.0%3Aoob&response_type=code&scope=https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive&state=state

Enter verification code:
```
Or maybe I'm dumb and don't understand something...

**Comment by vatavale** [comment]
My problem was that I did not use ./ before gdrive -)

**Comment by raspiduino** [comment]
To solve this, you must install `musl`
On Debian(-based), use `sudo apt install musl`
