### ISSUE TITLE
redirect_uri: urn:ietf:wg:oauth:2.0:oob ‪ error

### ISSUE THREAD

**Issue by markusgerber76** [prasmussen/gdrive#621]
new OAuth usage will be blocked for the OOB flow

All new gdrive commandline binaries compiled after Feb 28, 2022 are blocked. This needs some love!

https://developers.googleblog.com/2022/02/making-oauth-flows-safer.html

![1](https://user-images.githubusercontent.com/43269671/156786631-4d3c5827-3f90-42fa-b550-113131f2e8e2.png)

**Comment by avatar-lavventura** [comment]
I have asked a question converning this issue into superuser: https://superuser.com/questions/1720015/google-cloud-oauth-clients-in-test-mode-that-are-using-the-oauth-oob-flow

**Comment by avatar-lavventura** [comment]
@odenwal Your steps explain how to use gdrive nothing extra special. I was doing exact [steps](https://stackoverflow.com/questions/65396850/how-to-handle-app-is-temporarily-blocked-from-logging-in-with-your-google-accou/65507155#65507155) but your solution does not solve the problem for [Google Cloud: OAuth clients in test mode that are using the OAuth OOB flow](https://superuser.com/questions/1720015/google-cloud-oauth-clients-in-test-mode-that-are-using-the-oauth-oob-flow).

**Comment by odenwal** [comment]
Did you clone `git clone https://github.com/odenwal/gdrive` ? That stackoverflow link clones prasmussen/gdrive.git

**Comment by avatar-lavventura** [comment]
What's the difference on https://github.com/odenwal/gdrive?

**Comment by odenwal** [comment]
As a git user **please** see the commit history https://github.com/odenwal/gdrive and https://github.com/msfjarvis/gdrive

**Comment by avatar-lavventura** [comment]
Your https://github.com/odenwal/gdrive is just forked from https://github.com/msfjarvis/gdrive and you just added an image into `README.md`

**Comment by markusgerber76** [comment]
Thanks you https://github.com/odenwal/gdrive is just forked from https://github.com/msfjarvis/gdrive for fixing the redirect_uri: urn:ietf:wg:oauth:2.0:oob.
