### ISSUE TITLE
Feature Addition: Please add support for file deletion upon successful upload

### ISSUE THREAD

**Issue by kartrocket** [prasmussen/gdrive#63]
Hi

Please add a cli parameter to delete the file from the local drive ( source ) upon successful upload

**Comment by mralexgray** [comment]
+1  this would eliminate a litany of nasty scripts (which I'd be happy to contribute, although they are not in GO), for monitoring/reacting to uploads.

**Comment by prasmussen** [comment]
The `--delete` flag has been added to gdrive 2 which does this:

```
$ gdrive upload --delete foo.txt
Uploading foo.txt
Uploaded 0B3X9GlR6EmbnU0ZRSmFnTE1BRjA at 6.0 B/s, total 10.0 B
Removed foo.txt
```

**Comment by jlobos** [comment]
`--delete` feature in `--recursive` pls 🙏
