### ISSUE TITLE
Debian installation 

### ISSUE THREAD

**Issue by FPC25** [prasmussen/gdrive#636]
I download the gdrive_2.1.1_linux_amd64.tar.gz file, then installed using

sudo install gdrive /usr/local/bin/gdrive

but then occurs the error 

bash: /usr/local/bin/gdrive: Arquivo ou diretório inexistente

even with the specified file in the folder. I also tried using the  

wget -O drive https://drive.google.com/uc?id=0B3X9GlR6Embnb095MGxEYmJhY2c

but gives me the older version 1.9.0

someone can help me install the newest version please.

**Comment by cg2v** [comment]
It appears that 2.1.1 was built on alpine linux (or some other non-glibc based linux) and depends on the musl C library. 
musl is packaged for debian, so if you `sudo apt install musl`, the gdrive from gdrive_2.1.1_linux_amd64.tar.gz should run.

**Comment by FPC25** [comment]
That works! Thank you very much cg2v
