### ISSUE TITLE
Windows and External Proxy Server

### ISSUE THREAD

**Issue by susserj** [prasmussen/gdrive#66]
Hi
Is it possible when utilizing "drive-windows-386.exe v1.8.0" to tell the software to use an external proxy server? Ideally, it would work similarly to the way "wget" works via environment variables, or command line parameters.
Thanks

**Comment by fovea1959** [comment]
set http_proxy=

works for me.

**Comment by susserj** [comment]
Hello favea1959. 
I tried your suggestion and set my Windows cmd environment parameter to our proxy server and  now  gdrive for Windows is now working for me. Perhaps this is an undocumented feature.

Thanks again.
