### ISSUE TITLE
Gdrive is amazing and just works

### ISSUE THREAD

**Issue by chilicuil** [prasmussen/gdrive#67]
Hi,

I'd just wanted to say thank you, gdrive is amazing and just works (file upload, Linux), it's extremely simple to setup, I went from discovering it to use it in less than 5 minutes.

Thanks!

**Comment by wowaname** [comment]
totally an issue

**Comment by wowaname** [comment]
no really as someone who has a couple repos this is really kinda annoying

**Comment by prasmussen** [comment]
:)
