### ISSUE TITLE
drive-linux-386 v1.8.0 seems to be i686 

### ISSUE THREAD

**Issue by gknauf** [prasmussen/gdrive#70]
The drive-linux-386 binary crashes on a i586 embedded platform (Alix board with Geode CPU):

root@alix-voyage:~# ./drive
SIGILL: illegal instruction
PC=0x8050545

goroutine 1 [running, locked to thread]:
runtime.mapassign1(0x82a4720, 0x18736040, 0x83e2c80, 0x83e2c88)
        /usr/local/go/src/runtime/hashmap.go:455 +0x245 fp=0x18735f70 sp=0x18735f14
time.init()
        /usr/local/go/src/time/format.go:1152 +0x16e fp=0x18735fa0 sp=0x18735f70
os.init()
        /usr/local/go/src/os/types_notwin.go:25 +0x4f fp=0x18735fc8 sp=0x18735fa0
main.init()
        /Users/pii/dev/gopkg/src/github.com/prasmussen/gdrive/drive.go:170 +0x3f fp=0x18735fcc sp=0x18735fc8
runtime.main()
        /usr/local/go/src/runtime/proc.go:58 +0xbd fp=0x18735ff0 sp=0x18735fcc
runtime.goexit()
        /usr/local/go/src/runtime/asm_386.s:2287 +0x1 fp=0x18735ff4 sp=0x18735ff0

goroutine 2 [runnable]:
runtime.forcegchelper()
        /usr/local/go/src/runtime/proc.go:90
runtime.goexit()
        /usr/local/go/src/runtime/asm_386.s:2287 +0x1

goroutine 3 [runnable]:
runtime.bgsweep()
        /usr/local/go/src/runtime/mgc0.go:82
runtime.goexit()
        /usr/local/go/src/runtime/asm_386.s:2287 +0x1

eax     0x0
ebx     0x0
ecx     0x1873a000
edx     0x18736040
edi     0x23
esi     0x1873a007
ebp     0x0
esp     0x18735f14
eip     0x8050545
eflags  0x10246
cs      0x73
fs      0x0
gs      0x3f

root@alix-voyage:~# uname -a
Linux alix-voyage 3.16.7-ckt9-voyage #1 SMP Thu Apr 23 11:10:44 HKT 2015 i586 GNU/Linux

root@alix-voyage:~# cat /proc/cpuinfo
processor       : 0
vendor_id       : AuthenticAMD
cpu family      : 5
model           : 10
model name      : Geode(TM) Integrated Processor by AMD PCS
stepping        : 2
cpu MHz         : 498.060
cache size      : 128 KB
physical id     : 0
siblings        : 1
core id         : 0
cpu cores       : 1
apicid          : 0
initial apicid  : 0
fdiv_bug        : no
f00f_bug        : no
coma_bug        : no
fpu             : yes
fpu_exception   : yes
cpuid level     : 1
wp              : yes
flags           : fpu de pse tsc msr cx8 sep pge cmov clflush mmx mmxext 3dnowext 3dnow vmmcall
bogomips        : 996.12
clflush size    : 32
cache_alignment : 32
address sizes   : 32 bits physical, 32 bits virtual
power management:

running same binary with same Linux distro but powered by an Intel Pentium D Dualcore works fine ...
is it possible that you provide a true i585 binary?

**Comment by gknauf** [comment]
Update: I tried self to build a working binary and found that the golang toolchain (386 binary distro) already crashes exactly the same way; also tested now with a Pentium 3 with is even classified as i686 but the crash happens too ...; therefore I've created an issue for golang:
https://github.com/golang/go/issues/11631

For now I found a workaround to create a true 32-bit Linux gdrive binary which works with my processors by using the gccgo compiler:
go build -compiler gccgo -gccgoflags '-static-libgo' drive.go
although the resulting binary is really fat (>8MB), some brief testing shows all working so far; did list/upload/download/folder commands and all fine.

**Comment by gknauf** [comment]
Got reply to the golang issue - quote:
"Go assumes SSE2 by default in our official binaries. Set GO386=387 when building from source, per instructions at http://golang.org/doc/install/source."
I tried already to use this var when I compiled gdrive but that didnt work ...
I followed the advice and did build the Go toolchain from source with GO386=387 and that works now fine: the toolchain itself runs on my 32-bit processors (without SSE2 support), and so does the gdrive binary compiled with:
go build -ldflags '-s' drive.go
the size of this binary is with 4.6M now also acceptable. If someone else  needs a gdrive binary for older processors without SSE2 support you can download it here:
[drive-linux-386-387 v1.8.0](https://drive.google.com/uc?id=0BwBjwH9WlTLpNW40WXBDaFlGdVk)

**Comment by SimonHova** [comment]
I am using gdrive on an old computer; could you please compile a more current binary for me?
