### ISSUE TITLE
"Eternal Upload" when file size > space available

### ISSUE THREAD

**Issue by rdeavila** [prasmussen/gdrive#72]
Hi!

I know: I can check if my file fits on drive space before start the upload. But, if I don't do this, and start uploading a file bigger than the remaining drive space, the upload never ends, and never tell me any message.

It's possible to implement a error message when the upload exceeds the drive space?

Thank you.

**Comment by tkgermany** [comment]
Same issue here.
it opens more and more connections until the max open files limit is exceeded on linux and then quits, would like to see that fixed too

**Comment by prasmussen** [comment]
In gdrive 2 the upload will timeout when no data has been transferred for a while, I think that should solve this problem.
