### ISSUE TITLE
Hard coded address in drive.go -- Should avoid.

### ISSUE THREAD

**Issue by stplaydog** [prasmussen/gdrive#74]
import (
    "fmt"
    "github.com/prasmussen/gdrive/cli"
    "github.com/prasmussen/gdrive/gdrive"
    "github.com/prasmussen/gdrive/util"
    "github.com/prasmussen/google-api-go-client/googleapi"
    "github.com/voxelbrain/goptions"
    "os"
)

**Comment by prasmussen** [comment]
Not sure why this should be avoided.
