### ISSUE TITLE
Upload absolute Filepaths broken in 1.9.0

### ISSUE THREAD

**Issue by tkgermany** [prasmussen/gdrive#75]
in 1.6 i was able to upload a folder /data/mydata/foo even if i was in /temp or whereever by issuing 
gdrive upload -p <BaseFolderID>  -f /data/mydata/foo
If I do that in 1.9.0 I get
chdir /temp/foo: no such file or directory

Seems like it cuts of the directoryname to upload and then, instead of using my absolute filepath to change to, it tries to change down from the current diretory.

Temporary workaround is issuing the following before upload
cd $Uploadpath/..

**Comment by Drezzler** [comment]
@prasmussen  Apparently , this issue got fixed in windows by this - https://github.com/prasmussen/gdrive/issues/56 and broke it for Unix.

**Comment by prasmussen** [comment]
In gdrive 2 the chdir syscall is not used anymore and should have the same behaviour on both windows and unix.
