### ISSUE TITLE
Upload multiple file in directory

### ISSUE THREAD

**Issue by Gosokan** [prasmussen/gdrive#76]
How to upload multiple file in a directory?
Eg: I have directory /home/mydirectory which have 4 file: file1.gz, backup.zip, image.jpg, someapp.bin

I'm using ubuntu 12.04. Thanks before.

**Comment by Drezzler** [comment]
I am using "gdrive upload -f FILE/FOLDERLOCATION -p DRIVE-PARENT-FOLDER-ID"

Or you can check out "-f" option by running gdrive -h

**Comment by danielgomezrico** [comment]
It worked for me with `gdrive upload -f folder/* `
