### ISSUE TITLE
Duplicate files: every time i use "drive upload --share --file xyz" a duplicate "xyz" is created.

### ISSUE THREAD

**Issue by tonyroza** [prasmussen/gdrive#77]
A new id number is created for each copy of "xyz". I am using this to share a few spreadsheets however, the documents will be updated from time to time. I cannot figure out how to prevent the duplicates using this tool which means I cannot send some a link to a document and then update the document later.

**Comment by qzcw** [comment]
This would be a very important function. I'd like to backup multiple files automatically, i.e. mirror the local folder to Google Drive cloud.

**Comment by berna1995** [comment]
Yes, i would love gdrive to use Google Drive revision system for example.

**Comment by alpi-ua** [comment]
I also need this if it real.

**Comment by robertogomez** [comment]
@tonyroza The behavior you're seeing is how Google Drive works. It doesn't uniquely identify files by name.

User occho made a [fork](0BytCbNhl3nyPelYtNGNzdlEtbkU) to add an update file feature, which is what I believe you and others have been looking for. I tested it briefly and it works, although I had to change some of the imports to build the binary correctly. Example:

    drive.exe upload -u 0BytCbNhl3nyPelYtNGNzdlEtbkU -f time.txt

**Comment by berna1995** [comment]
@robertogomez Can you please upload a compiled version of that specific fork? Im not able to compile the source.

**Comment by Drezzler** [comment]
@berna - Are you using golang v1.4.2 when compliling gdrive ?

It is the only version i have ever used to compile gdrive with , and it has always worked (tried with v1.5.2 , but was getting errors).

**Comment by berna1995** [comment]
@Drezzler I tried the last version on Linux. Have you suceeded compiling with v.1.4.2?

**Comment by occho** [comment]
@berna1995 Hi
I uploaded executables I made with golang v1.4.2. https://drive.google.com/file/d/0B5wVSvViMOXmSGVmdFlUX0dtVm8/view?usp=sharing
I will remove it at some later point.

**Comment by berna1995** [comment]
@occho Thank you very much. I'll test later. :+1:

**Comment by Arvur** [comment]
@occho Works like a charm for me! Thanks a lot! :+1:

**Comment by prasmussen** [comment]
gdrive 2 supports updating files: `gdrive update 0B3X9GlR6EmbnNTk0SkV0bm5Hd0E gdrive-osx-x64`.
