### ISSUE TITLE
More share options

### ISSUE THREAD

**Issue by Loreinator** [prasmussen/gdrive#78]
Is it possible for you to allow multiple share options, instead of just private or everyone from the internet? I tend to like to share so only people with the link can view, or alternatively so only people with the link can edit something. Having it so open in the only sharing option is a bit odd, considering how many choices google drive gives us.

Just an argument to the --share argument on the upload command is fine, even if its just a number or a couple letters.

**Comment by prasmussen** [comment]
In gdrive 2 `gdrive share` gives you more control on how the file is shared. `upload --share` still gives read access to anyone, but it is not discoverable by default anymore.
