### ISSUE TITLE
Feature Request:  Support downloading by query

### ISSUE THREAD

**Issue by rbeede** [prasmussen/gdrive#82]
It'd be nice if I could skip specifying an --id and just pass --query directly to the download command instead.   It should support downloading multiple files/folders of anything that matched.

**Comment by prasmussen** [comment]
gdrive 2 supports downloading by query: `gdrive download query --recursive "name contains 'gdrive'"`

Note that some files might be downloaded multiple times when using the recursive flag though. I.e. if you have a file named gdrive inside a gdrive folder – it will be downloaded as a single file and as a subfile of the folder. I might fix this in the future.
