### ISSUE TITLE
Progress indicator

### ISSUE THREAD

**Issue by combucha** [prasmussen/gdrive#83]
Hi, would it be possible to implement some simple live percentage progress upload (/download) indicator?
I'm kinda blind during uploading large files, dunno how many data is already transferred...

**Comment by kmand** [comment]
I also would find this valuable!

**Comment by sloth77** [comment]
If you are in a position to build yourself, you can add a simple progress output yourself by chaining a googleapi.ProgressUpdater function of your own to the FilesInsertCall call chain.  Basically, I added a function:

<pre>
func progCb(current, total int64) {
    fmt.Printf("Progress: %.2f%%, %d/%d bytes                     \r", 
               float64(current)/float64(total))*100.0,current,total)
}
</pre>

to gdrive\cli\cli.go

and then referenced it in the uploadFile call:

<pre>info, err := d.Files.Insert(f).Convert(convert).
                ResumableMedia(context.Background(), input, inputInfo.Size(), mimeType).
                <b>ProgressUpdater(progCb)</b>.Do()</pre>

By the way - I should add that whilst I'm a programmer, I know zilch about Go and this is a complete hack.  It worked for me, but if it deletes all your files, don't blame me :-)

**Comment by user501254** [comment]
@prasmussen this would be great. Progress indicators for downloads and uploads are an absolute necessity when using the command in external scripts. The blinking cursor looks really poor. 

@sloth77, maybe you could generate a pull request to help.

**Comment by combucha** [comment]
@sloth77 this can't work, code has syntax error: cli.go: unexpected ), expecting := or = or comma
I fixed it, but my new build goes without visible progress info, just like old one...
Could you paste your whole cli.go somewhere?
Matbe it's my system fault, xp :\

**Comment by sloth77** [comment]
Hi @combucha.  File is listed below.  Had to rename it to get past the filter.

[cli.go.txt](https://github.com/prasmussen/gdrive/files/46783/cli.go.txt)

One thing I found is that you need to use Go <=1.4.2 or you get compilation errors with the Google API stuff.  That might have been what you were hitting.

Also, I have a pre-built Windows binary if that is of use?

**Comment by combucha** [comment]
Thanks @sloth77 
Working :-) It worked before too, I was just impatient, on my console progress monitor appears 30 seconds after upload start and is refreshed the same period also.
What about download part?

**Comment by sloth77** [comment]
Yeah, I didn't need download so I never bothered.  Also, its a different API, so the same ProgressUpdater hook wont work.  Probably one for the maintainer.....

**Comment by alvarokid** [comment]
@sloth77 I've installed gdrive running "cd && sudo install drive-linux* /usr/local/bin/drive" from it's binnary and I couldn't find cli.go and the other files to include your function, where are they supposed to be?

**Comment by Grauen** [comment]
progressbar for uploads would be a great benefit. I got to upload lots of files and it kinda feels wrong doing it without steady feedback :).

**Comment by prasmussen** [comment]
gdrive 2 has a basic progress indicator enabled by default for larger files.

**Comment by arkarkark** [comment]
using this would be neat https://github.com/schollz/progressbar
I understand this bug is closed, but I thought this comment would make it more complete.
