### ISSUE TITLE
Is it possible to change account?

### ISSUE THREAD

**Issue by thebaddie** [prasmussen/gdrive#84]
Let's say I have one or more Google Drive accounts, how can I switch between them?

**Comment by Drezzler** [comment]
You can set the option for using a specific config file which will contain account specific details .

**Comment by eddOrnelas** [comment]
How this can be done?

**Comment by prasmussen** [comment]
`gdrive -c foo list`
This will look for a token.json inside the directory `foo`. If the directory does not exist, it will be created and prompt you for a new verification code.

**Comment by JuliArianes** [comment]
@prasmussen i have try gdrive -c foo list . but if i try command "gdrive list"  ==> the list is my old account ... how to change account???
