### ISSUE TITLE
Uploads speeds are really slow [Google changes?]

### ISSUE THREAD

**Issue by Drezzler** [prasmussen/gdrive#86]
Is anyone else dealing with slow upload speeds ?

I am on a Gbit connection and the upload speeds are under 1Mbps , I tried with some other drive command line clients for linux , but having same problem with all of them.

Did google make changes to its api or somehting ?

**Comment by thebaddie** [comment]
Same issue here

Upload speed decreased from 25 MB/s to 20KB/s

**Comment by Drezzler** [comment]
I only started having problems since yesterday , even tried some other repos (https://github.com/odeke-em/drive) , but even that did not help .

Tested with latest version of gdrive (v1.9) and that seems to be little on the ok side since it supports setting upload chunk size , but its still too damn slow ...

Sometimes upload completes but gdrive just hangs up and waits for a long time before actually completing the job.

@thebaddie - since when are you having this problem ?

**Comment by iamxie** [comment]
Same issue +1
Upload speed decreased from 20 MB/s to 1MB/s

**Comment by Drezzler** [comment]
So my speed is back to normal , infact better ... getting really really good speeds now
