### ISSUE TITLE
Upload Speed

### ISSUE THREAD

**Issue by kmand** [prasmussen/gdrive#87]
I find that the upload speed with this program is about 25% of what I get with the
Google browser based upload on the same Linux machine. I want to cron some very large daily uploads
that would be difficult using the browser.

Any suggestions on how to speed it up? I see relatively little user/system time, just a lot of real
time on the command line drive.

**Comment by Drezzler** [comment]
What version of gdrive are you using ?

If it is >1.6 , may be you can have a look at this https://github.com/prasmussen/gdrive/issues/49

**Comment by kmand** [comment]
Thanks, with an increased block size I can get the same upload speed as the browser gets.
