### ISSUE TITLE
problem working with cron

### ISSUE THREAD

**Issue by pozirk** [prasmussen/gdrive#88]
Hello!

I'm using this wonderful tool to backup my server files, but I have a problem doing this automatically with cron.
I've entered verification code, but when drive runs by cron job, it asks for verification code again.
Are there anything I've missed?

Thank you!

**Comment by Drezzler** [comment]
What is your OS ?

It is probably a persmission issue , are you running the cron job and commad line , commands as the same user ?

**Comment by pozirk** [comment]
I'm using CentOS 6.7.
I tried drive in command line under root with no problems.
My cron task looks like this:
> 10 03 * * 2 root /home/backup.sh

**Comment by rdeavila** [comment]
I've seen this before on #55...

**Comment by pozirk** [comment]
Thank you for your people!
I have found the problem, but in my case it was a bit different.
When I run drive myself, it creates token file in **/root/.gdrive**, but with cron task it creates file in **/.gdrive**.
I just don't know, why it uses different passes.

**Comment by Drezzler** [comment]
You can give a config path i think , with --config option ?

`-c, --config       Set application path where config and token is stored. Defaults to ~/.gdrive`

Have you tried that ?

**Comment by pozirk** [comment]
I have tried to change config path to some other, and it was changed fine.
But when cron task runs drive it still uses config at **/.gdrive**.
This is not a big problem, just wonder why it is so.

**Comment by gneissone** [comment]
I experienced the same problem with a cron job, but setting the -c flag worked fine for me. Glad I found this discussion, it saved me a big headache.
