### ISSUE TITLE
Feature request - Add a timeout ?

### ISSUE THREAD

**Issue by Drezzler** [prasmussen/gdrive#91]
Since drive api hangs up every now and then , it would be nice to have a timeout set or a manual timeout set , so that a timeout error is returned. @prasmussen

**Comment by prasmussen** [comment]
gdrive 2 will timeout when no data has been transferred for a while, I think this will solve the problem. The timeout is 2 minutes for now, but I might add a flag that can override the timeout if needed.

Thanks for helping out answering issues btw :)

**Comment by Drezzler** [comment]
Is there an error returned when timeout occurs ?

I love the new options/features you have added to gdrive and it looks like compiling from source will be much more easier now .

Thank you so much for this awesome tool .

**Comment by prasmussen** [comment]
Yes, gdrive should exit with exit code 1 and write an error message on stderr. The message at the moment is "context canceled", I will change this to something more suitable in the future.
