### ISSUE TITLE
file or info option needed to show a file/folder's "path"

### ISSUE THREAD

**Issue by mralexgray** [prasmussen/gdrive#93]
Most people are going to have a local "working copy" of their drive (or at least some of it).

I'm hoping an option can be added to `info` or `file` that simply walks up the hierarchy of `info --id` -> `parent` to show _some kind_  (even if imperfect) guess at the rough location of a file (by id) in the folder structure..

I know that 'google drive' is *not* a file system - in the traditional sense.. but as most people CAN navigate it that way (and more often than not, THINK about it that way)... It would be nice to show some kind of representation of files' locations.

For example.. the following three commands would equal the path

`/My Drive/Louis Theroux`

```
drive list -t Theroux
Id                             Title                                 Size       Created
0B3swL5sLfqGwa0lCcmVvTGZKTDA   Louis Theroux                         0.0 B      2015-08-22 20:25:30

drive info -i 0B3swL5sLfqGwa0lCcmVvTGZKTDA
Id: 0B3swL5sLfqGwa0lCcmVvTGZKTDA
Title: Louis Theroux
Size: 0.0 B
Parents: 0AHswL5sLfqGwUk9PVA

drive info -i 0AHswL5sLfqGwUk9PVA
Id: 0AHswL5sLfqGwUk9PVA
Title: My Drive
```

**Comment by prasmussen** [comment]
In gdrive 2 `gdrive info` will show the path of the first parent.
I've also added a `--absolute` flag to `gdrive list` which will show the full path in the listing.
