### ISSUE TITLE
gdrive list

### ISSUE THREAD

**Issue by ewleonardspock** [prasmussen/gdrive#96]
I'm having trouble using gdrive.  List does not seem to be working.  I run "gdrive list" and it spins the gear in the tab for a few seconds to indicate that it's doing something, then it stops and never returns anything, it doesn't crash either.  
![screen shot 2015-12-03 at 8 39 28 pm](https://cloud.githubusercontent.com/assets/5833157/11579688/168b37b6-99fe-11e5-97e6-b4a9060d0b23.png)

**Comment by Drezzler** [comment]
If you have a lot of files or sync/uploads (to drive) going on , its best to use `-m` parameter to limit the number of results , as fetching a lot of results will probably get stuck due to google drives api timeout restrictions.

example `gdrive list -m 10`

**Comment by eduardo4jesus** [comment]
I am getting this error when doing:

> drive pull -export pdf -no-prompt --fix-clashes

By the way, last time I tried to pull all my files, it said the clashes were fixed, but I would have to call it again. Is there a flag to automatically run it again in these case?
